name: Deploy website

on:
    push:
        branches: ["source"]

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set Node.js
              uses: actions/setup-node@4
              with:
                  node-version: 20
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Setup Pages
              id: pages
              uses: actions/configure-pages@v5

            - name: Upload artifacts
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./public
