name: Deploy website

on:
    push:
        branches:
            - source

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Set Node.js
              uses: actions/setup-node@master
              with:
                  node-version: 18

            - uses: actions/checkout@v1

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: master
                  publish_dir: ./public
