name: Deploy website

on:
    push:
        branches: ["source"]

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set Node.js
              uses: actions/setup-node@master
              with:
                  node-version: 20
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Upload artifacts
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./public
